package billing

// FocusData represents a single row in an OCI FOCUS report.
type FocusData struct {
	AvailabilityZone           string
	BilledCost                 string
	BillingAccountId           string
	BillingAccountName         string
	BillingCurrency            string
	BillingPeriodEnd           string
	BillingPeriodStart         string
	ChargeCategory             string
	ChargeDescription          string
	ChargeFrequency            string
	ChargePeriodEnd            string
	ChargePeriodStart          string
	ChargeSubcategory          string
	CommitmentDiscountCategory string
	CommitmentDiscountId       string
	CommitmentDiscountName     string
	CommitmentDiscountType     string
	EffectiveCost              string
	InvoiceIssuer              string
	ListCost                   string
	ListUnitPrice              string
	PricingCategory            string
	PricingQuantity            string
	PricingUnit                string
	Provider                   string
	Publisher                  string
	Region                     string
	ResourceId                 string
	ResourceName               string
	ResourceType               string
	ServiceCategory            string
	ServiceName                string
	SkuId                      string
	SkuPriceId                 string
	SubAccountId               string
	SubAccountName             string
	Tags                       string
	UsageQuantity              string
	UsageUnit                  string
	OciReferenceNumber         string
	OciCompartmentId           string
	OciCompartmentName         string
	OciOverageFlag             string
	OciUnitPriceOverage        string
	OciBilledQuantityOverage   string
	OciCostOverage             string
	OciAttributedUsage         string
	OciAttributedCost          string
	OciBackReferenceNumber     string
}
